using System.Collections.Generic;
using Andastra.Runtime.Core.Interfaces;
using Andastra.Runtime.Core.Interfaces.Components;

namespace Andastra.Game.Games.Eclipse.Components
{
    /// <summary>
    /// Eclipse Engine (Dragon Age Origins, Dragon Age 2) specific sound component implementation.
    /// </summary>
    /// <remarks>
    /// Eclipse Sound Component:
    /// - Based on daorigins.exe and DragonAge2.exe sound system
    /// - Eclipse engines use similar sound entity system to Odyssey/Aurora engines
    /// - Sound entities emit positional audio in the game world
    /// - Uses UTS file format (GFF with "UTS " signature) for sound templates, same as Odyssey/Aurora
    /// - Sound properties: Active, Continuous, Looping, Positional, Random, RandomPosition
    /// - Volume and distance: Volume (0-127), VolumeVrtn, MaxDistance, MinDistance
    /// - Timing: Interval, IntervalVrtn, PitchVariation
    /// - Sound files: List of sound ResRefs for playback
    /// - Hours: Bitmask for time-based activation (0-23 hour range)
    /// - GeneratedType: 0 = manually placed, 1 = autogenerated from area ambient sound
    /// 
    /// Cross-engine analysis:
    /// - Odyssey (swkotor.exe, swkotor2.exe): Uses SoundComponent with UTS GFF templates
    ///   - SoundList @ 0x007bd080 (GIT sound list), Sound @ 0x007bc500 (sound entity type)
    ///   - 0x004e08e0 @ 0x004e08e0 loads sound instances from GIT
    /// - Aurora (nwmain.exe, nwn2main.exe): Uses AuroraSoundComponent with similar UTS format
    ///   - CNWSSoundObject class for sound entities
    /// - Eclipse (daorigins.exe, DragonAge2.exe): Uses EclipseSoundComponent with UTS format
    ///   - Sound entities loaded from area files (SAV format) SoundList
    ///   - Sound properties stored in SAV area files, similar structure to Odyssey/Aurora
    ///   - Both games use identical sound system with same properties and behavior
    /// 
    /// Reverse Engineering Notes (Ghidra MCP verified):
    /// - daorigins.exe: Sound entity creation and loading functions
    ///   - String references found: "SoundList", "Sound", "Active", "Looping", "Volume", "MaxDistance", "MinDistance"
    ///   - Sound entities are loaded from GIT file "SoundList" (GFFList, StructID 6) during area loading
    ///   - Sound properties loaded from GIT sound instances: Position, ResRef, and from UTS templates
    ///   - Sound properties: Active, Continuous, Looping, Positional, Random, RandomPosition, Volume, VolumeVrtn, MaxDistance, MinDistance, Interval, IntervalVrtn, PitchVariation, Sounds list, Hours, GeneratedType
    ///   - Implementation: Sound entities created in area loading code (similar to Odyssey pattern at 0x004e08e0)
    ///   - Function addresses: Sound loading is integrated into area GIT parsing, not a separate function
    /// - DragonAge2.exe: Enhanced sound system (compatible with daorigins.exe)
    ///   - String references found: "SoundList" @ 0x00bf1a48, "Sound" @ 0x00bf8abc, "Active" @ 0x00bf85b8, "Looping" @ 0x00c0c7b4
    ///   - Sound entities loaded from GIT file "SoundList" (same format as daorigins.exe)
    ///   - Binary format: Compatible with daorigins.exe, uses same GIT/UTS structure
    ///   - Implementation: Sound loading integrated into area GIT parsing system
    ///   - Function addresses: Sound loading is integrated into area GIT parsing, not a separate function
    /// - Cross-engine comparison: Compare daorigins.exe and DragonAge2.exe implementations
    ///   to identify common patterns and engine-specific differences
    /// - Note: Sound entity creation/loading is handled by area loading code that parses GIT files
    ///   - EclipseArea.LoadEntities() loads sounds from GIT.Sounds list
    ///   - Sound entities created with ObjectType.Sound and EclipseSoundComponent attached
    ///   - Properties initialized from GIT sound instance data and UTS template files
    /// 
    /// Component attachment:
    /// - Attached during entity creation from area templates (SAV files)
    /// - Properties initialized from SAV SoundList entries
    /// - Can be attached manually via EclipseEntity.AttachSoundComponents
    /// 
    /// Sound playback:
    /// - Uses ISoundPlayer interface for actual audio playback
    /// - Positional sounds use transform component position for 3D spatial audio
    /// - Volume adjusted based on distance from listener (distance falloff)
    /// - Looping sounds play continuously while active
    /// - Random sounds select from SoundFiles list randomly
    /// - Interval-based sounds play at specified intervals (with variation)
    /// - Hours bitmask controls time-based activation (0-23 hours)
    /// </remarks>
    public class EclipseSoundComponent : ISoundComponent
    {
        public IEntity Owner { get; set; }

        public void OnAttach() { }
        public void OnDetach() { }

        /// <summary>
        /// Creates a new Eclipse sound component with default values.
        /// </summary>
        /// <remarks>
        /// Default initialization:
        /// - TemplateResRef: Empty string
        /// - SoundFiles: Empty list
        /// - Volume: 100 (out of 127 max)
        /// - MaxDistance: 50.0f (meters)
        /// - MinDistance: 1.0f (meters)
        /// - Active: false
        /// - Continuous: false
        /// - Looping: false
        /// - Positional: true (3D spatial audio)
        /// - Random: false
        /// - RandomPosition: false
        /// - VolumeVrtn: 0
        /// - Interval: 0
        /// - IntervalVrtn: 0
        /// - PitchVariation: 0.0f
        /// - Hours: 0 (no time-based activation)
        /// - GeneratedType: 0 (manually placed)
        /// - TimeSinceLastPlay: 0.0f
        /// - IsPlaying: false
        /// </remarks>
        public EclipseSoundComponent()
        {
            TemplateResRef = string.Empty;
            SoundFiles = new List<string>();
            Volume = 100;
            MaxDistance = 50f;
            MinDistance = 1f;
            Active = false;
            Continuous = false;
            Looping = false;
            Positional = true;
            Random = false;
            RandomPosition = false;
            VolumeVrtn = 0;
            Interval = 0;
            IntervalVrtn = 0;
            PitchVariation = 0.0f;
            Hours = 0;
            GeneratedType = 0;
            TimeSinceLastPlay = 0.0f;
            IsPlaying = false;
        }

        /// <summary>
        /// Template resource reference (UTS file).
        /// </summary>
        /// <remarks>
        /// ResRef of the UTS (sound template) file used to create this sound entity.
        /// Loaded from area files (SAV format) or set manually.
        /// </remarks>
        public string TemplateResRef { get; set; }

        /// <summary>
        /// Whether the sound is active and should play.
        /// </summary>
        /// <remarks>
        /// When Active is false, the sound will not play even if other conditions are met.
        /// Set to true to enable sound playback.
        /// </remarks>
        public bool Active { get; set; }

        /// <summary>
        /// Whether the sound is continuous (plays continuously when active).
        /// </summary>
        /// <remarks>
        /// Continuous sounds play repeatedly without intervals.
        /// Different from Looping: Continuous replays the sound immediately, Looping plays one continuous loop.
        /// </remarks>
        public bool Continuous { get; set; }

        /// <summary>
        /// Whether the sound loops (plays in a continuous loop).
        /// </summary>
        /// <remarks>
        /// Looping sounds play continuously without stopping until Active is set to false or stopped.
        /// Different from Continuous: Looping plays one continuous loop, Continuous replays the sound immediately.
        /// </remarks>
        public bool Looping { get; set; }

        /// <summary>
        /// Whether the sound is positional (3D spatial audio).
        /// </summary>
        /// <remarks>
        /// Positional sounds use the entity's transform component position for 3D spatial audio.
        /// Volume is adjusted based on distance from listener using distance falloff (MinDistance to MaxDistance).
        /// Non-positional sounds play as 2D audio at full volume regardless of listener position.
        /// </remarks>
        public bool Positional { get; set; }

        /// <summary>
        /// Whether to randomize the sound position.
        /// </summary>
        /// <remarks>
        /// RandomPosition adds random offset to the sound position for each play.
        /// Used to create more natural ambient sound effects.
        /// </remarks>
        public bool RandomPosition { get; set; }

        /// <summary>
        /// Whether to play random sounds from the SoundFiles list.
        /// </summary>
        /// <remarks>
        /// When Random is true, a random sound from SoundFiles is selected for each play.
        /// When Random is false, sounds are played in sequence or a single sound is played.
        /// </remarks>
        public bool Random { get; set; }

        /// <summary>
        /// Volume level (0-127).
        /// </summary>
        /// <remarks>
        /// Volume range: 0 (silent) to 127 (maximum).
        /// Actual playback volume is affected by VolumeVrtn (random variation) and distance falloff (for positional sounds).
        /// </remarks>
        public int Volume { get; set; }

        /// <summary>
        /// Volume variation (random adjustment to volume).
        /// </summary>
        /// <remarks>
        /// VolumeVrtn adds random variation to the base Volume for each play.
        /// Range: Typically 0-127, added/subtracted from base Volume.
        /// </remarks>
        public int VolumeVrtn { get; set; }

        /// <summary>
        /// Maximum audible distance (meters).
        /// </summary>
        /// <remarks>
        /// For positional sounds, volume decreases from full volume at MinDistance to zero at MaxDistance.
        /// Sounds beyond MaxDistance are not audible.
        /// </remarks>
        public float MaxDistance { get; set; }

        /// <summary>
        /// Minimum distance for full volume (meters).
        /// </summary>
        /// <remarks>
        /// For positional sounds, volume is at full level (adjusted by Volume) when listener is within MinDistance.
        /// Volume decreases linearly from MinDistance to MaxDistance.
        /// </remarks>
        public float MinDistance { get; set; }

        /// <summary>
        /// Interval between plays (seconds).
        /// </summary>
        /// <remarks>
        /// For non-looping, non-continuous sounds, Interval specifies the time between plays.
        /// Actual interval is Interval +/- IntervalVrtn (random variation).
        /// </remarks>
        public uint Interval { get; set; }

        /// <summary>
        /// Interval variation (random adjustment to interval).
        /// </summary>
        /// <remarks>
        /// IntervalVrtn adds random variation to the base Interval for each play.
        /// Actual interval is Interval +/- IntervalVrtn.
        /// </remarks>
        public uint IntervalVrtn { get; set; }

        /// <summary>
        /// Pitch variation (random pitch adjustment).
        /// </summary>
        /// <remarks>
        /// PitchVariation adds random pitch variation to each sound play.
        /// Range: Typically 0.0f to 1.0f, affects playback speed/pitch.
        /// </remarks>
        public float PitchVariation { get; set; }

        /// <summary>
        /// List of sound file resource references.
        /// </summary>
        /// <remarks>
        /// SoundFiles contains the list of sound ResRefs to play.
        /// For Random sounds, a random entry is selected for each play.
        /// For non-random sounds, entries are played in sequence or a single sound is played.
        /// </remarks>
        public List<string> SoundFiles { get; set; }

        /// <summary>
        /// Hours when sound is active (bitmask, 0-23).
        /// </summary>
        /// <remarks>
        /// Hours is a bitmask where each bit represents an hour (0-23).
        /// If a bit is set, the sound can play during that hour.
        /// If Hours is 0, the sound can play at any time (time-based activation disabled).
        /// </remarks>
        public uint Hours { get; set; }

        /// <summary>
        /// Time since last play (seconds).
        /// </summary>
        /// <remarks>
        /// Used internally for interval-based sound playback.
        /// Tracks elapsed time since the last sound play to determine when to play next.
        /// </remarks>
        public float TimeSinceLastPlay { get; set; }

        /// <summary>
        /// Whether the sound is currently playing.
        /// </summary>
        /// <remarks>
        /// IsPlaying indicates if the sound is currently being played by the audio system.
        /// Used to track playback state and prevent overlapping plays.
        /// </remarks>
        public bool IsPlaying { get; set; }

        /// <summary>
        /// Generated type flag (0 = manually placed, 1 = autogenerated from area ambient sound).
        /// </summary>
        /// <remarks>
        /// GeneratedType (Eclipse):
        /// - 0: Sound instance was manually placed by module builder in toolset
        /// - 1: Sound instance was autogenerated by Area Properties dialog as part of area's Ambient Day or Ambient Night sound
        /// - If GeneratedType is 1, the sound instance may be subject to automatic deletion when user picks a different ambient sound for the area
        /// 
        /// Based on Aurora pattern: CNWSSoundObject::Save stores GeneratedType
        /// Eclipse engines likely use similar pattern for area ambient sound management.
        /// </remarks>
        public int GeneratedType { get; set; }
    }
}

