using System.Collections.Generic;
using Andastra.Runtime.Core.Interfaces;
using Andastra.Runtime.Core.Interfaces.Components;

namespace Andastra.Game.Games.Aurora.Components
{
    /// <summary>
    /// Aurora Engine (Neverwinter Nights) specific sound component implementation.
    /// </summary>
    /// <remarks>
    /// Aurora Sound Component:
    /// - Based on nwmain.exe sound system (CNWSSoundObject class)
    /// - Located via string references: "SoundList" @ 0x140ddb7b0 (GIT sound list)
    /// - CNWSArea::LoadSounds @ 0x140362260 loads sound instances from GIT
    /// - CNWSSoundObject::Save @ 0x1404f54c0 saves sound data to GFF
    /// - CNWSSoundObject::Load @ 0x1404f4b60 loads sound data from GFF
    /// - CNWSSoundObject constructor @ 0x1404f3600 initializes sound object with default values
    /// 
    /// CNWSSoundObject Structure (nwmain.exe):
    /// - Offset 0x308: Active (BYTE, default 1)
    /// - Offset 0x30c: Positional (BYTE, default 1)
    /// - Offset 0x310: Looping (BYTE, default 0)
    /// - Offset 0x314: Volume (BYTE, default 0x7f = 127, range 0-127)
    /// - Offset 0x318: VolumeVrtn (BYTE, default 0)
    /// - Offset 0x31c: Times (BYTE, default 3, number of times to play)
    /// - Offset 0x320: PitchVariation (FLOAT, default 0.0f)
    /// - Offset 0x324: Hours (DWORD, default 0, bitmask for time-based activation 0-23)
    /// - Offset 0x328: GeneratedType (BYTE, default 0, 0=manually placed, 1=autogenerated)
    /// - Offset 0x32c: RandomPosition (BYTE, default 0)
    /// - Offset 0x330: RandomRangeX (FLOAT, default 0.0f)
    /// - Offset 0x334: RandomRangeY (FLOAT, default 0.0f)
    /// - Offset 0x338: Sounds list pointer (pointer to CExoArrayList of CResRef)
    /// - Offset 0x340: Sounds count (int, number of sounds in list)
    /// - Offset 0x348: Interval (DWORD, default 0, seconds between plays)
    /// - Offset 0x34c: IntervalVrtn (DWORD, default 0, interval variation)
    /// - Offset 0x350: MinDistance (FLOAT, default 10.0f, minimum distance for full volume)
    /// - Offset 0x354: MaxDistance (FLOAT, default 20.0f, maximum audible distance)
    /// - Offset 0x358: Continuous (BYTE, default 0)
    /// - Offset 0x35c: Random (BYTE, default 0)
    /// 
    /// GFF Field Names (from CNWSSoundObject::Save @ 0x1404f54c0):
    /// - Tag: CExoString (loaded from GIT)
    /// - Active: BYTE
    /// - Positional: BYTE
    /// - Looping: BYTE
    /// - Volume: BYTE (0-127)
    /// - VolumeVrtn: BYTE
    /// - Times: BYTE (number of times to play, typically 3)
    /// - PitchVariation: FLOAT
    /// - Hours: DWORD (bitmask 0-23)
    /// - GeneratedType: DWORD (stored as BYTE, 0=manually placed, 1=autogenerated)
    /// - Interval: DWORD (seconds)
    /// - IntervalVrtn: DWORD (variation in seconds)
    /// - MinDistance: FLOAT
    /// - MaxDistance: FLOAT
    /// - Continuous: BYTE
    /// - Random: BYTE
    /// - RandomPosition: BYTE
    /// - RandomRangeX: FLOAT
    /// - RandomRangeY: FLOAT
    /// - XPosition, YPosition, ZPosition: FLOAT (from transform component)
    /// - Sounds: List of structs with "Sound" CResRef field
    /// 
    /// Sound entities emit positional audio in the game world.
    /// Uses UTS file format (GFF with "UTS " signature) for sound templates.
    /// Sound properties: Active, Continuous, Looping, Positional, Random, RandomPosition
    /// Volume and distance: Volume (0-127), VolumeVrtn, MaxDistance, MinDistance
    /// Timing: Interval, IntervalVrtn, PitchVariation
    /// Sound files: List of sound ResRefs for playback
    /// Hours: Bitmask for time-based activation (0-23 hour range)
    /// GeneratedType: 0 = manually placed, 1 = autogenerated from area ambient sound
    /// 
    /// Cross-engine analysis:
    /// - Odyssey (swkotor.exe, swkotor2.exe): Uses SoundComponent with UTS GFF templates
    ///   - SoundList @ 0x007bd080 (GIT sound list), Sound @ 0x007bc500 (sound entity type)
    ///   - FUN_004e08e0 @ 0x004e08e0 loads sound instances from GIT
    /// - Aurora (nwmain.exe): Uses AuroraSoundComponent with similar UTS format
    ///   - CNWSSoundObject class for sound entities
    ///   - CNWSArea::LoadSounds @ 0x140362260 loads sound list from GIT
    ///   - CNWSSoundObject constructor @ 0x1404f3600 initializes with defaults
    /// - Eclipse (daorigins.exe, DragonAge2.exe): Uses EclipseSoundComponent with UTS format
    ///   - Sound entities loaded from area files (SAV format) SoundList
    /// 
    /// Component attachment:
    /// - Attached during entity creation from area templates (GIT files)
    /// - Properties initialized from GIT SoundList entries and UTS template files
    /// - Can be attached manually via AuroraEntity.AttachSoundComponents
    /// 
    /// Sound playback:
    /// - Uses ISoundPlayer interface for actual audio playback
    /// - Positional sounds use transform component position for 3D spatial audio
    /// - Volume adjusted based on distance from listener (distance falloff)
    /// - Looping sounds play continuously while active
    /// - Random sounds select from SoundFiles list randomly
    /// - Interval-based sounds play at specified intervals (with variation)
    /// - Hours bitmask controls time-based activation (0-23 hours)
    /// - Continuous sounds play repeatedly without intervals
    /// </remarks>
    public class AuroraSoundComponent : ISoundComponent
    {
        public IEntity Owner { get; set; }

        public void OnAttach() { }
        public void OnDetach() { }

        /// <summary>
        /// Creates a new Aurora sound component with default values matching nwmain.exe CNWSSoundObject constructor.
        /// </summary>
        /// <remarks>
        /// Default initialization (based on nwmain.exe CNWSSoundObject constructor @ 0x1404f3600):
        /// - TemplateResRef: Empty string
        /// - SoundFiles: Empty list
        /// - Active: true (default 1 at offset 0x308)
        /// - Positional: true (default 1 at offset 0x30c, 3D spatial audio)
        /// - Looping: false (default 0 at offset 0x310)
        /// - Volume: 127 (default 0x7f at offset 0x314, maximum volume)
        /// - VolumeVrtn: 0 (default 0 at offset 0x318)
        /// - MaxDistance: 20.0f (default 0x41a00000 = 20.0f at offset 0x354, meters)
        /// - MinDistance: 10.0f (default 0x41200000 = 10.0f at offset 0x350, meters)
        /// - Continuous: false (default 0 at offset 0x358)
        /// - Random: false (default 0 at offset 0x35c)
        /// - RandomPosition: false (default 0 at offset 0x32c)
        /// - VolumeVrtn: 0 (default 0 at offset 0x318)
        /// - Interval: 0 (default 0 at offset 0x348, seconds)
        /// - IntervalVrtn: 0 (default 0 at offset 0x34c, seconds)
        /// - PitchVariation: 0.0f (default 0.0f at offset 0x320)
        /// - Hours: 0 (default 0 at offset 0x324, no time-based activation)
        /// - GeneratedType: 0 (default 0 at offset 0x328, manually placed)
        /// - TimeSinceLastPlay: 0.0f
        /// - IsPlaying: false
        /// </remarks>
        public AuroraSoundComponent()
        {
            TemplateResRef = string.Empty;
            SoundFiles = new List<string>();
            Active = true;
            Positional = true;
            Looping = false;
            Volume = 127;
            VolumeVrtn = 0;
            MaxDistance = 20.0f;
            MinDistance = 10.0f;
            Continuous = false;
            Random = false;
            RandomPosition = false;
            Interval = 0;
            IntervalVrtn = 0;
            PitchVariation = 0.0f;
            Hours = 0;
            GeneratedType = 0;
            TimeSinceLastPlay = 0.0f;
            IsPlaying = false;
        }

        /// <summary>
        /// Template resource reference (UTS file).
        /// </summary>
        /// <remarks>
        /// ResRef of the UTS (sound template) file used to create this sound entity.
        /// Loaded from area GIT files (SoundList entries) or set manually.
        /// Based on nwmain.exe: TemplateResRef loaded from GIT SoundList struct.
        /// </remarks>
        public string TemplateResRef { get; set; }

        /// <summary>
        /// Whether the sound is active and should play.
        /// </summary>
        /// <remarks>
        /// When Active is false, the sound will not play even if other conditions are met.
        /// Set to true to enable sound playback.
        /// Based on nwmain.exe: Active stored at offset 0x308 in CNWSSoundObject (BYTE, default 1).
        /// Saved to GFF as "Active" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 22).
        /// </remarks>
        public bool Active { get; set; }

        /// <summary>
        /// Whether the sound is continuous (plays continuously when active).
        /// </summary>
        /// <remarks>
        /// Continuous sounds play repeatedly without intervals.
        /// Different from Looping: Continuous replays the sound immediately, Looping plays one continuous loop.
        /// Based on nwmain.exe: Continuous stored at offset 0x358 in CNWSSoundObject (BYTE, default 0).
        /// Saved to GFF as "Continuous" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 35).
        /// </remarks>
        public bool Continuous { get; set; }

        /// <summary>
        /// Whether the sound loops (plays in a continuous loop).
        /// </summary>
        /// <remarks>
        /// Looping sounds play continuously without stopping until Active is set to false or stopped.
        /// Different from Continuous: Looping plays one continuous loop, Continuous replays the sound immediately.
        /// Based on nwmain.exe: Looping stored at offset 0x310 in CNWSSoundObject (BYTE, default 0).
        /// Saved to GFF as "Looping" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 24).
        /// </remarks>
        public bool Looping { get; set; }

        /// <summary>
        /// Whether the sound is positional (3D spatial audio).
        /// </summary>
        /// <remarks>
        /// Positional sounds use the entity's transform component position for 3D spatial audio.
        /// Volume is adjusted based on distance from listener using distance falloff (MinDistance to MaxDistance).
        /// Non-positional sounds play as 2D audio at full volume regardless of listener position.
        /// Based on nwmain.exe: Positional stored at offset 0x30c in CNWSSoundObject (BYTE, default 1).
        /// Saved to GFF as "Positional" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 23).
        /// </remarks>
        public bool Positional { get; set; }

        /// <summary>
        /// Whether to randomize the sound position.
        /// </summary>
        /// <remarks>
        /// RandomPosition adds random offset to the sound position for each play.
        /// Used to create more natural ambient sound effects.
        /// Based on nwmain.exe: RandomPosition stored at offset 0x32c in CNWSSoundObject (BYTE, default 0).
        /// Saved to GFF as "RandomPosition" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 37).
        /// RandomRangeX and RandomRangeY (offsets 0x330 and 0x334) define the random position range.
        /// </remarks>
        public bool RandomPosition { get; set; }

        /// <summary>
        /// Whether to play random sounds from the SoundFiles list.
        /// </summary>
        /// <remarks>
        /// When Random is true, a random sound from SoundFiles is selected for each play.
        /// When Random is false, sounds are played in sequence or a single sound is played.
        /// Based on nwmain.exe: Random stored at offset 0x35c in CNWSSoundObject (BYTE, default 0).
        /// Saved to GFF as "Random" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 36).
        /// </remarks>
        public bool Random { get; set; }

        /// <summary>
        /// Volume level (0-127).
        /// </summary>
        /// <remarks>
        /// Volume range: 0 (silent) to 127 (maximum).
        /// Actual playback volume is affected by VolumeVrtn (random variation) and distance falloff (for positional sounds).
        /// Based on nwmain.exe: Volume stored at offset 0x314 in CNWSSoundObject (BYTE, default 0x7f = 127).
        /// Saved to GFF as "Volume" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 25).
        /// </remarks>
        public int Volume { get; set; }

        /// <summary>
        /// Volume variation (random adjustment to volume).
        /// </summary>
        /// <remarks>
        /// VolumeVrtn adds random variation to the base Volume for each play.
        /// Range: Typically 0-127, added/subtracted from base Volume.
        /// Based on nwmain.exe: VolumeVrtn stored at offset 0x318 in CNWSSoundObject (BYTE, default 0).
        /// Saved to GFF as "VolumeVrtn" BYTE field (CNWSSoundObject::Save @ 0x1404f54c0 line 26).
        /// </remarks>
        public int VolumeVrtn { get; set; }

        /// <summary>
        /// Maximum audible distance (meters).
        /// </summary>
        /// <remarks>
        /// For positional sounds, volume decreases from full volume at MinDistance to zero at MaxDistance.
        /// Sounds beyond MaxDistance are not audible.
        /// Based on nwmain.exe: MaxDistance stored at offset 0x354 in CNWSSoundObject (FLOAT, default 20.0f).
        /// Saved to GFF as "MaxDistance" FLOAT field (CNWSSoundObject::Save @ 0x1404f54c0 line 34).
        /// </remarks>
        public float MaxDistance { get; set; }

        /// <summary>
        /// Minimum distance for full volume (meters).
        /// </summary>
        /// <remarks>
        /// For positional sounds, volume is at full level (adjusted by Volume) when listener is within MinDistance.
        /// Volume decreases linearly from MinDistance to MaxDistance.
        /// Based on nwmain.exe: MinDistance stored at offset 0x350 in CNWSSoundObject (FLOAT, default 10.0f).
        /// Saved to GFF as "MinDistance" FLOAT field (CNWSSoundObject::Save @ 0x1404f54c0 line 33).
        /// </remarks>
        public float MinDistance { get; set; }

        /// <summary>
        /// Interval between plays (seconds).
        /// </summary>
        /// <remarks>
        /// For non-looping, non-continuous sounds, Interval specifies the time between plays.
        /// Actual interval is Interval +/- IntervalVrtn (random variation).
        /// Based on nwmain.exe: Interval stored at offset 0x348 in CNWSSoundObject (DWORD, default 0).
        /// Saved to GFF as "Interval" DWORD field (CNWSSoundObject::Save @ 0x1404f54c0 line 31).
        /// </remarks>
        public uint Interval { get; set; }

        /// <summary>
        /// Interval variation (random adjustment to interval).
        /// </summary>
        /// <remarks>
        /// IntervalVrtn adds random variation to the base Interval for each play.
        /// Actual interval is Interval +/- IntervalVrtn.
        /// Based on nwmain.exe: IntervalVrtn stored at offset 0x34c in CNWSSoundObject (DWORD, default 0).
        /// Saved to GFF as "IntervalVrtn" DWORD field (CNWSSoundObject::Save @ 0x1404f54c0 line 32).
        /// </remarks>
        public uint IntervalVrtn { get; set; }

        /// <summary>
        /// Pitch variation (random pitch adjustment).
        /// </summary>
        /// <remarks>
        /// PitchVariation adds random pitch variation to each sound play.
        /// Range: Typically 0.0f to 1.0f, affects playback speed/pitch.
        /// Based on nwmain.exe: PitchVariation stored at offset 0x320 in CNWSSoundObject (FLOAT, default 0.0f).
        /// Saved to GFF as "PitchVariation" FLOAT field (CNWSSoundObject::Save @ 0x1404f54c0 line 28).
        /// </remarks>
        public float PitchVariation { get; set; }

        /// <summary>
        /// List of sound file resource references.
        /// </summary>
        /// <remarks>
        /// SoundFiles contains the list of sound ResRefs to play.
        /// For Random sounds, a random entry is selected for each play.
        /// For non-random sounds, entries are played in sequence or a single sound is played.
        /// Based on nwmain.exe: Sounds stored as CExoArrayList at offset 0x338 in CNWSSoundObject.
        /// Count stored at offset 0x340. Each entry is a CResRef (17 bytes).
        /// Saved to GFF as "Sounds" list with "Sound" CResRef fields (CNWSSoundObject::Save @ 0x1404f54c0 lines 43-52).
        /// </remarks>
        public List<string> SoundFiles { get; set; }

        /// <summary>
        /// Hours when sound is active (bitmask, 0-23).
        /// </summary>
        /// <remarks>
        /// Hours is a bitmask where each bit represents an hour (0-23).
        /// If a bit is set, the sound can play during that hour.
        /// If Hours is 0, the sound can play at any time (time-based activation disabled).
        /// Based on nwmain.exe: Hours stored at offset 0x324 in CNWSSoundObject (DWORD, default 0).
        /// Saved to GFF as "Hours" DWORD field (CNWSSoundObject::Save @ 0x1404f54c0 line 29).
        /// </remarks>
        public uint Hours { get; set; }

        /// <summary>
        /// Time since last play (seconds).
        /// </summary>
        /// <remarks>
        /// Used internally for interval-based sound playback.
        /// Tracks elapsed time since the last sound play to determine when to play next.
        /// Not stored in GFF (runtime-only state).
        /// </remarks>
        public float TimeSinceLastPlay { get; set; }

        /// <summary>
        /// Whether the sound is currently playing.
        /// </summary>
        /// <remarks>
        /// IsPlaying indicates if the sound is currently being played by the audio system.
        /// Used to track playback state and prevent overlapping plays.
        /// Not stored in GFF (runtime-only state).
        /// </remarks>
        public bool IsPlaying { get; set; }

        /// <summary>
        /// Generated type flag (0 = manually placed, 1 = autogenerated from area ambient sound).
        /// </summary>
        /// <remarks>
        /// GeneratedType (Aurora):
        /// - 0: Sound instance was manually placed by module builder in toolset
        /// - 1: Sound instance was autogenerated by Area Properties dialog as part of area's Ambient Day or Ambient Night sound
        /// - If GeneratedType is 1, the sound instance is subject to automatic deletion when user picks a different ambient sound for the area
        /// - Stored as DWORD in GFF but is actually a BYTE value (0-1)
        /// 
        /// Based on nwmain.exe: CNWSSoundObject::Save @ 0x1404f54c0 line 30
        /// - GeneratedType stored at offset 0x328 in CNWSSoundObject structure (BYTE, default 0)
        /// - Written as DWORD: CResGFF::WriteFieldDWORD(param_1, param_2, (uint)(byte)this[0x328], "GeneratedType")
        /// - Based on vendor/PyKotor/wiki/Bioware-Aurora-SoundObject.md: Table 2.3
        /// </remarks>
        public int GeneratedType { get; set; }
    }
}

